get_order_detail_response = {
    "error": "",
    "message": "",
    "response": {
        "order_list": [
            {
                "actual_shipping_fee": 0,
                "actual_shipping_fee_confirmed": False,
                "buyer_cancel_reason": "",
                "buyer_cpf_id": None,
                "buyer_user_id": 28215,
                "buyer_username": "sandbox_buyer.0364d9064946b2",
                "cancel_by": "",
                "cancel_reason": "",
                "checkout_shipping_carrier": "Standard Delivery - ส่งธรรมดาในประเทศ",
                "cod": False,
                "create_time": 1635903675,
                "credit_card_number": None,
                "currency": "THB",
                "days_to_ship": 2,
                "dropshipper": "",
                "dropshipper_phone": "",
                "estimated_shipping_fee": 0,
                "fulfillment_flag": "fulfilled_by_local_seller",
                "goods_to_declare": False,
                "invoice_data": None,
                "item_list": [
                    {
                        "item_id": 101566054,
                        "item_name": "Cat",
                        "item_sku": "",
                        "model_id": 20009246845,
                        "model_name": "White,Fat",
                        "model_sku": "wf",
                        "model_quantity_purchased": 1,
                        "model_original_price": 50,
                        "model_discounted_price": 50,
                        "wholesale": False,
                        "weight": 0.5,
                        "add_on_deal": False,
                        "main_item": False,
                        "add_on_deal_id": 0,
                        "promotion_type": "",
                        "promotion_id": 0,
                        "order_item_id": 101566054,
                        "promotion_group_id": 0,
                        "image_info": {
                            "image_url": "https://cf.shopee.co.th/file/5250d4da05f015cc630323c5f0dd5770_tn"
                        },
                    },
                    {
                        "item_id": 101566054,
                        "item_name": "Cat",
                        "item_sku": "",
                        "model_id": 20009246847,
                        "model_name": "Black,Fat",
                        "model_sku": "bf",
                        "model_quantity_purchased": 1,
                        "model_original_price": 50,
                        "model_discounted_price": 50,
                        "wholesale": False,
                        "weight": 0.5,
                        "add_on_deal": False,
                        "main_item": False,
                        "add_on_deal_id": 0,
                        "promotion_type": "",
                        "promotion_id": 0,
                        "order_item_id": 101566054,
                        "promotion_group_id": 0,
                        "image_info": {
                            "image_url": "https://cf.shopee.co.th/file/61cd08e4112e75090e09ec07fdc31fc8_tn"
                        },
                    },
                    {
                        "item_id": 101566054,
                        "item_name": "Cat",
                        "item_sku": "",
                        "model_id": 20009246848,
                        "model_name": "Black,Not Fat",
                        "model_sku": "bn",
                        "model_quantity_purchased": 1,
                        "model_original_price": 60,
                        "model_discounted_price": 60,
                        "wholesale": False,
                        "weight": 0.5,
                        "add_on_deal": False,
                        "main_item": False,
                        "add_on_deal_id": 0,
                        "promotion_type": "",
                        "promotion_id": 0,
                        "order_item_id": 101566054,
                        "promotion_group_id": 0,
                        "image_info": {
                            "image_url": "https://cf.shopee.co.th/file/61cd08e4112e75090e09ec07fdc31fc8_tn"
                        },
                    },
                    {
                        "item_id": 101566054,
                        "item_name": "Cat",
                        "item_sku": "",
                        "model_id": 20009248886,
                        "model_name": "Black,Super,Fat",
                        "model_sku": "",
                        "model_quantity_purchased": 1,
                        "model_original_price": 50,
                        "model_discounted_price": 50,
                        "wholesale": False,
                        "weight": 0.5,
                        "add_on_deal": False,
                        "main_item": False,
                        "add_on_deal_id": 0,
                        "promotion_type": "",
                        "promotion_id": 0,
                        "order_item_id": 101566054,
                        "promotion_group_id": 0,
                        "image_info": {
                            "image_url": "https://cf.shopee.co.th/file/61cd08e4112e75090e09ec07fdc31fc8_tn"
                        },
                    },
                    {
                        "item_id": 101566054,
                        "item_name": "Cat",
                        "item_sku": "",
                        "model_id": 20009248887,
                        "model_name": "White,Super,Fat",
                        "model_sku": "",
                        "model_quantity_purchased": 1,
                        "model_original_price": 800,
                        "model_discounted_price": 800,
                        "wholesale": False,
                        "weight": 0.5,
                        "add_on_deal": False,
                        "main_item": False,
                        "add_on_deal_id": 0,
                        "promotion_type": "",
                        "promotion_id": 0,
                        "order_item_id": 101566054,
                        "promotion_group_id": 0,
                        "image_info": {
                            "image_url": "https://cf.shopee.co.th/file/5250d4da05f015cc630323c5f0dd5770_tn"
                        },
                    },
                ],
                "message_to_seller": "Can you declaw them please?",
                "note": "",
                "note_update_time": 0,
                "order_sn": "211103HHF2HJ42",
                "order_status": "READY_TO_SHIP",
                "package_list": [
                    {
                        "package_number": "OFG89602879139352",
                        "logistics_status": "LOGISTICS_NOT_START",
                        "shipping_carrier": "Standard Delivery - ส่งธรรมดาในประเทศ",
                        "item_list": [
                            {"item_id": 101566054, "model_id": 20009246845},
                            {"item_id": 101566054, "model_id": 20009246847},
                            {"item_id": 101566054, "model_id": 20009246848},
                            {"item_id": 101566054, "model_id": 20009248886},
                            {"item_id": 101566054, "model_id": 20009248887},
                        ],
                    }
                ],
                "pay_time": 1635903724,
                "payment_method": "Online Payment",
                "pickup_done_time": 0,
                "recipient_address": {
                    "name": "Buyer",
                    "phone": "66988888888",
                    "town": "",
                    "district": "",
                    "city": "เขตสาทร",
                    "state": "จังหวัดกรุงเทพมหานคร",
                    "region": "TH",
                    "zipcode": "10120",
                    "full_address": "283/2, ซอย จันทน์ 18/7, Thung Wat Don เขตสาทร จังหวัดกรุงเทพมหานคร TH 10120",
                },
                "region": "TH",
                "reverse_shipping_fee": 0,
                "ship_by_date": 1636076524,
                "shipping_carrier": "",
                "split_up": False,
                "total_amount": 1010,
                "update_time": 1635903724,
            }
        ]
    },
    "request_id": "7e6941f176e1516c119e21b8aa9a83a3",
}
