get_escrow_detail_response = {
    "request_id": "4be80e3a8ed5ce394530a4a3ebe9d742",
    "error": "",
    "message": "",
    "response": {
        "order_sn": "211103HHF2HJ42",
        "buyer_user_name": "sandbox_buyer.0364d9064946b2",
        "return_order_sn_list": [],
        "order_income": {
            "escrow_amount": 1010,
            "buyer_total_amount": 1010,
            "original_price": 1010,
            "seller_discount": 0,
            "shopee_discount": 0,
            "voucher_from_seller": 0,
            "voucher_from_shopee": 0,
            "coins": 0,
            "buyer_paid_shipping_fee": 0,
            "buyer_transaction_fee": 0,
            "cross_border_tax": 0,
            "payment_promotion": 0,
            "commission_fee": 0,
            "service_fee": 0,
            "seller_transaction_fee": 0,
            "seller_lost_compensation": 0,
            "seller_coin_cash_back": 0,
            "escrow_tax": 0,
            "final_shipping_fee": 0,
            "actual_shipping_fee": 0,
            "shopee_shipping_rebate": 0,
            "shipping_fee_discount_from_3pl": 0,
            "seller_shipping_discount": 0,
            "estimated_shipping_fee": 0,
            "seller_voucher_code": [],
            "drc_adjustable_refund": 0,
            "cost_of_goods_sold": 1010,
            "original_cost_of_goods_sold": 1010,
            "original_shopee_discount": 0,
            "seller_return_refund": 0,
            "reverse_shipping_fee": 0,
            "items": [
                {
                    "item_id": 101566054,
                    "item_name": "Cat",
                    "item_sku": "",
                    "model_id": 20009246845,
                    "model_name": "White,Fat",
                    "model_sku": "wf",
                    "original_price": 50,
                    "discounted_price": 50,
                    "discount_from_coin": 0,
                    "discount_from_voucher_shopee": 0,
                    "discount_from_voucher_seller": 0,
                    "activity_type": "",
                    "is_main_item": False,
                    "activity_id": 0,
                },
                {
                    "item_id": 101566054,
                    "item_name": "Cat",
                    "item_sku": "",
                    "model_id": 20009246847,
                    "model_name": "Black,Fat",
                    "model_sku": "bf",
                    "original_price": 50,
                    "discounted_price": 50,
                    "discount_from_coin": 0,
                    "discount_from_voucher_shopee": 0,
                    "discount_from_voucher_seller": 0,
                    "activity_type": "",
                    "is_main_item": False,
                    "activity_id": 0,
                },
                {
                    "item_id": 101566054,
                    "item_name": "Cat",
                    "item_sku": "",
                    "model_id": 20009246848,
                    "model_name": "Black,Not Fat",
                    "model_sku": "bn",
                    "original_price": 60,
                    "discounted_price": 60,
                    "discount_from_coin": 0,
                    "discount_from_voucher_shopee": 0,
                    "discount_from_voucher_seller": 0,
                    "activity_type": "",
                    "is_main_item": False,
                    "activity_id": 0,
                },
                {
                    "item_id": 101566054,
                    "item_name": "Cat",
                    "item_sku": "",
                    "model_id": 20009248886,
                    "model_name": "Black,Super,Fat",
                    "model_sku": "",
                    "original_price": 50,
                    "discounted_price": 50,
                    "discount_from_coin": 0,
                    "discount_from_voucher_shopee": 0,
                    "discount_from_voucher_seller": 0,
                    "activity_type": "",
                    "is_main_item": False,
                    "activity_id": 0,
                },
                {
                    "item_id": 101566054,
                    "item_name": "Cat",
                    "item_sku": "",
                    "model_id": 20009248887,
                    "model_name": "White,Super,Fat",
                    "model_sku": "",
                    "original_price": 800,
                    "discounted_price": 800,
                    "discount_from_coin": 0,
                    "discount_from_voucher_shopee": 0,
                    "discount_from_voucher_seller": 0,
                    "activity_type": "",
                    "is_main_item": False,
                    "activity_id": 0,
                },
            ],
        },
    },
}
