### ArteryPartner.co,.ltd. ###

# SECTION : Basic Info 

# ANCHOR: using Docker Executor

# TODO : Create Test Stage for develop branch
# TODO : Set up pre-define Environment variable
# TODO : using gitlab CI variable 

# REVIEW : Environment VAR
# !SECTION

# SECTION : Read ME 

# Environment variable 
# https://docs.gitlab.com/ee/ci/variables/

# Predefined environment variables
# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html 

# Using docker images
# https://docs.gitlab.com/ee/ci/docker/using_docker_images.html

# .gitlab-ci.yml reference
# https://docs.gitlab.com/ee/ci/yaml/

# Container registry reference (authenticating, etc.)
# https://gitlab.com/help/user/packages/container_registry/index
# !SECTION 

# SECTION :CI-Header
# ANCHOR : Define CI stage & Share variable

stages:
  - build
  - test

# NOTE : In Frappe framework application CD stage will run in frappe-docker CI/CD

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/shopee_open_api:$CI_COMMIT_SHORT_SHA
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

image: docker:latest

services:
  - docker:dind

before_script:
  - apk add git
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled


# !SECTION

# SECTION : Define a job in each stage
# ANCHOR : Test Stage for python (lint & unit Test)

lint_test:
  image: python:3.8.0-slim
  stage: test
  before_script:
    - pip install flake8-html
  script:
    - flake8 --format=html --htmldir=flake_reports/
  artifacts:
    when: always
    paths:
      - flake_reports/

pytest:
  image: python:3.8.0-slim
  stage: test
  before_script:
   # - pip install pytest-html
  #  - pip install -r requirements.txt
  script:
  #  - pytest --html=pytest_reports/pytest-report.html --self-contained-html
  artifacts:
    when: always
    paths:
      - pytest_reports/

# ANCHOR : Build Stage
# NOTE : Frappe framework run build stage to build two image (nginx & worker)

build_shopee_open_api_nginx:
  stage: build
  only:
    - tags
  script:
    - export VERSION=$(git tag --list --sort=-version:refname | sed -n 1p | sed -e 's#.*@\(\)#\1#')
    - docker build -t excel-erpnext-nginx docker/excel-erpnext-nginx
    - docker tag excel-erpnext-nginx "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-nginx:$VERSION"
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-nginx:$VERSION"

   # - docker pull $CI_REGISTRY_IMAGE:latest || true
   # - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
   # - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
   # - docker push $CI_REGISTRY_IMAGE:latest


build_shopee_open_api_worker:
  stage: build
  only:
    - tags
  script:
    - export VERSION=$(git tag --list --sort=-version:refname | sed -n 1p | sed -e 's#.*@\(\)#\1#')
    - docker build -t excel-erpnext-worker docker/excel-erpnext-worker
    - docker tag excel-erpnext-worker "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-worker:$VERSION"
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-worker:$VERSION"

build_staging_shopee_open_api_nginx:
  stage: build
  only:
    refs:
      - version-13
  script:
    - docker build -t excel-erpnext-nginx docker/excel-erpnext-nginx
    - docker tag excel-erpnext-nginx "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-nginx:latest"
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-nginx:latest"

build_staging_shopee_open_api_worker:
  stage: build
  only:
    refs:
      - version-13
  script:
    - docker build -t excel-erpnext-worker docker/excel-erpnext-worker
    - docker tag excel-erpnext-worker "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-worker:latest"
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-worker:latest"
# !SECTION

